import { Achievement } from "@/types/achievement";
import { Activity } from "@/types/activity";
import { Course } from "@/types/course";
import { User } from "@/types/user";

export const testCourses: Course[] = [
  {
    id: "ABC123",
    name: "Test course name",
    status: "active",
    instructor: "Sergio Angel",
    activities: 2,
    submissions: 3,
  },
  {
    id: "XYZ456",
    name: "Another course",
    status: "active",
    instructor: "Sergio Angel",
    activities: 2,
    submissions: 3,
  },
];

export const testUsers: User[] = [
  {
    id: "U001",
    name: "Sergio",
    phonenumber: "+573001234567",
    email: "sergio@correo.com",
    role: "student",
    status: "active",
    xp: 123,
    level: 20,
    average: 85,
    missions: 5,
    streak: 3,
  },
  {
    id: "U002",
    name: "Ana Paez",
    phonenumber: "+573002345678",
    email: "ana@correo.com",
    role: "student",
    status: "active",
    xp: 98,
    level: 15,
    average: 90,
    missions: 3,
    streak: 2,
  },
  {
    id: "U003",
    name: "Luis Martinez",
    phonenumber: "+573003456789",
    email: "luis@correo.com",
    role: "student",
    status: "inactive",
    xp: 200,
    level: 30,
    average: 88,
    missions: 8,
    streak: 5,
  },
  {
    id: "U004",
    name: "Camila Gomez",
    phonenumber: "+573004567890",
    email: "camila@correo.com",
    role: "student",
    status: "active",
    xp: 75,
    level: 12,
    average: 70,
    missions: 2,
    streak: 1,
  },
  {
    id: "U005",
    name: "Jorge Lopez",
    phonenumber: "+573005678901",
    email: "jorge@correo.com",
    role: "student",
    status: "active",
    xp: 155,
    level: 24,
    average: 92,
    missions: 6,
    streak: 4,
  },
  {
    id: "U006",
    name: "Laura Ramirez",
    phonenumber: "+573006789012",
    email: "laura@correo.com",
    role: "student",
    status: "active",
    xp: 185,
    level: 28,
    average: 95,
    missions: 7,
    streak: 6,
  },
  {
    id: "U007",
    name: "Sofia Castro",
    phonenumber: "+573007890123",
    email: "sofia@correo.com",
    role: "student",
    status: "inactive",
    xp: 115,
    level: 19,
    average: 78,
    missions: 4,
    streak: 2,
  },
  {
    id: "U008",
    name: "Admin User",
    phonenumber: "+573008901234",
    email: "admin@correo.com",
    role: "admin",
    status: "active",
    xp: 300,
    level: 50,
    average: 100,
    missions: 10,
    streak: 10,
  },
];

export const testAchievements: Achievement[] = [
  {
    id: "A001",
    name: "Logro 1",
    img: "uploads/logro.png",
  },
];

export const testActivities: Activity[] = [
  {
    id: "A001",
    name: "Test Activity",
    description: "This is a test activity",
    attachment: "uploads/archivo.mp4",
    assignedTo: [
      {
        id: "ABC123",
        name: "Test course name",
        status: "active",
        instructor: "Sergio Angel",
        activities: 2,
        submissions: 3,
      },
    ],
    xp: 2000,
    achievements: [
      {
        id: "A001",
        name: "Logro 1",
        img: "uploads/logro.png",
      },
    ],
  },
];
